import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'SyntaxSaga',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
